description: CSpell Configuration
version: "0.2"
enabled: true
allowCompoundWords: true
useGitignore: true
validateDirectives: true
language: en-US
enabledLanguageIds:
  - markdown
  - python
  - shellscript
dictionaries:
  - aws
  - node
  - npm
  - python
ignorePaths:
  - .gitattributes
  - .gitignore
  - .pre-commit-config.yaml
  - .tool-versions
  - .vscode/extensions.json
  - .vscode/settings.json
  - cspell.config.yaml
  - package.json
  - pyproject.toml
  - .idea/*
words:
  - fargate
  - kibibytes
  - tqdm
